global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-notes-tl4r.onrender.com']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']