name: Docker Image Publish & Render Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-notes:latest

      - name: Retag with current date and push
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/fastapi-notes
          DATE_TAG=$(date -u +"%Y-%m-%d-%H%M")
          echo "Tagging image with date: $DATE_TAG"
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$DATE_TAG
          docker push $IMAGE_NAME:$DATE_TAG

      - name: Log out from Docker Hub
        run: docker logout

      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}